openapi: 3.0.0

info:
  title: FindAz
  version: "1.0"
  description: FindAz marketplace

servers:
  - url: http://127.0.0.1:8080

paths:
  /api/items:
    get:
      operationId: app.items.controller.get_items
      responses:
        200:
          description: Returns list of product
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string

    post:
      operationId: app.items.controller.post_item
      responses:
        201:
          description: Returns product id

  /api/items/{item_id}:
    get:
      operationId: app.items.controller.get_item
      responses:
        200:
          description: Returns one product
    put:
      operationId: app.items.controller.put_image_to_item
      responses:
        200:
          description: Returns added images url

  /{file}:
    get:
      operationId: app.items.controller.get_image
      responses:
        200:
          description: Returns image

components:
  schemas:
    getItemsSchema:
      type: object
      properties:
        items:
          type: array
          items:
            type: object
            properties:
              _id:
                type: string
              image_url:
                type: string
              title:
                type: string
              time_added:
                type: string
              image0_url:
                type: string
              image1_url:
                type: string
              image2_url:
                type: string
              main_file_url:
                type: string
            required:
              - _id
              - title
              - image_url
              - time_added
              - main_file_url
      additionalProperties: false
      required:
        - items
