"""empty message

Revision ID: 4d4ceae06dfa
Revises: 7e280b0657d0
Create Date: 2023-06-18 13:47:42.334648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d4ceae06dfa'
down_revision = '7e280b0657d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shop_shop_owner_id'), ['shop_owner_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_shop_owner_id'))

    # ### end Alembic commands ###
