"""empty message

Revision ID: 61451a55bb0b
Revises: 
Create Date: 2023-06-04 01:14:48.997295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61451a55bb0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('findaz',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('edit_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('owner', sa.String(length=50), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('properties', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('findaz')
    # ### end Alembic commands ###
