"""product model update

Revision ID: 6520540eb3aa
Revises: aa0bb44c8682
Create Date: 2024-01-03 00:30:35.894534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6520540eb3aa'
down_revision = 'aa0bb44c8682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_tags', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('product_rating', sa.DECIMAL(), nullable=True))
        batch_op.add_column(sa.Column('product_price', sa.DECIMAL(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('product_price')
        batch_op.drop_column('product_rating')
        batch_op.drop_column('product_tags')

    # ### end Alembic commands ###
