"""empty message

Revision ID: 7e280b0657d0
Revises: 8bcdaacc9489
Create Date: 2023-06-17 21:33:13.860008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e280b0657d0'
down_revision = '8bcdaacc9489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop',
    sa.Column('shop_title', sa.String(length=50), nullable=True),
    sa.Column('shop_owner_id', sa.UUID(), nullable=True),
    sa.Column('shop_photo', sa.String(length=50), nullable=True),
    sa.Column('shop_tags', postgresql.ARRAY(sa.String(), dimensions=6), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('edit_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop')
    # ### end Alembic commands ###
