"""empty message

Revision ID: 8bcdaacc9489
Revises: 0142d863affb
Create Date: 2023-06-14 18:31:45.075276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bcdaacc9489'
down_revision = '0142d863affb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_black_list', schema=None) as batch_op:
        batch_op.drop_constraint('token_black_list_access_token_key', type_='unique')
        batch_op.drop_constraint('token_black_list_refresh_token_key', type_='unique')
        batch_op.drop_column('access_token')
        batch_op.drop_column('refresh_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_black_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token', sa.VARCHAR(length=800), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('access_token', sa.VARCHAR(length=800), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('token_black_list_refresh_token_key', ['refresh_token'])
        batch_op.create_unique_constraint('token_black_list_access_token_key', ['access_token'])

    # ### end Alembic commands ###
